### ISSUE TITLE
multimarkdown doesn't build on win32 (mingw32) without modifications

### ISSUE THREAD

**Issue by Alexey-Yakovenko** [fletcher/MultiMarkdown-4#102]
things missing:

* windows makefile target is not compatible with native win32 - it's using the "/usr/bin/i586-mingw32msvc-cc" instead of $(CC)
* strndup function is missing (used in transclude.c)
* strtok.h needs to be included in the parser.leg

the makefile can be fixed like this:

```
windows: parser.c
	$(CC) -c -Wall -O3 *.c
	$(CC) *.o -Wl,--dy -o multimarkdown.exe
```

some random strndup implementation under MIT license [can be found here](http://markmail.org/message/sf2rxhjuza3k7gdi#query:+page:1+mid:xma3ikw7tg7vzhj3+state:results).

**Comment by fletcher** [comment]
The windows target is designed for compiling on *nix for Windows. 

F

-- 
Fletcher T. Penney
fletcher@fletcherpenney.net

**Comment by Alexey-Yakovenko** [comment]
Yes, but these simple fixes would let it build on windows too.

**Comment by fletcher** [comment]
I haven't tested, but I believe that would break building on *nix.  That's the entire reason the windows target exists.

**Comment by Alexey-Yakovenko** [comment]
I can't really see whether you're interested in making this work, or you actually want to keep it broken.
Pls let me know if you want to get windows build work on windows, and I'll make a patch, and make sure it works on both windows+mingw32 and linux+mingw32.
If not, just close the ticket, and I'll keep the fixes to myself :)

**Comment by fletcher** [comment]
Again -- the `make windows` command is designed to build for Windows, on a *nix machine.  It's not designed for compiling on a Windows machine.

**Comment by Alexey-Yakovenko** [comment]
I know that from the comment in the makefile.
Replacing /usr/bin/i586-mingw32msvc-cc with $(CC), and setting the CC environment variable correctly, is a very common way of implementing cross-compilation support.
All you'd have to change is put CC=/usr/bin/i586-mingw32msvc-cc into your build script on a unix machine, before running "make windows".

**Comment by mn4367** [comment]
In #91 I used a plain vanilla MSYS/MinGW installation on Windows 7. The only problem I had was the missing `strtok_r` function error. Adding
```c
#if defined(__WIN32)
#include "strtok.c"
#endif 
```
in `parser.leg` solved the problem for me and building went fine (although I don't know if that's really correct, but with `strtok.h` it didn't work).

The binary is fairly large (1.4 MB) but with `strip multimarkdown.exe` the size is about the same as that from the official builds.

**Comment by fletcher** [comment]
MultiMarkdown 5 is now available, and is using CMake to control the build process.  As always, the expectation is to use `make` or `make debug` (for example), regardless of the OS.  `make windows` is specifically for the use case of cross-compiling for Windows on a non-Windows system (e.g. Linux) with MinGW.  I'm not interested in debating the terminology of that point.  ;)

What I _am_ interested in is that `make` should work on _almost_ any OS, including Windows.  If you have problems with getting MMD-5 to compile on Windows, then please let me know. 

Closing this as MMD-4 is now deprecated, and future development on these lines should occur in MMD-5.

Thanks!
