### ISSUE TITLE
extracting the node tree

### ISSUE THREAD

**Issue by mlilback** [fletcher/MultiMarkdown-4#103]
One difference between this and the previous version is that, for programs using libmultimarkdown.a, there is no way to easily get a node tree of what was parsed.

**Comment by fletcher** [comment]
Sorry for the delay -- trying to go back through old issues/pull requests....

Sure you can.  Just look at `markdown_to_string()` and stop before the `export_node_tree()` function.

Maybe one day I'll refactor the code to split the logic out, but it's all there.
