### ISSUE TITLE
fancy lists (letters instead of numbers)

### ISSUE THREAD

**Issue by adamfeuer** [fletcher/MultiMarkdown-4#117]
Would you be interested in a pull request that would add fancy lists to MultiMarkDown? This would be similar to [Pandoc's fancy_lists plugin](http://pandoc.org/demo/example19/Extension-fancy_005flists.html).

I need this functionality for a book I am writing.

**Comment by fletcher** [comment]
Changing which markers are used for lists (numbers, letters, symbols, etc.) is a function of output formatting, not the Markdown/MMD input.  This can be changed via HTML/CSS, or LaTeX, etc.

I don't plan on adding multiple variants of list markers on the MMD *input* side -- use numbers and then modify your output as desired.

But you are certainly welcome to link to your own repo/source for others who might want to add the feature to their own copy.

Thanks for sharing!!
