### ISSUE TITLE
Well formed HTML/XML with missing figure definition

### ISSUE THREAD

**Issue by mn4367** [fletcher/MultiMarkdown-4#121]
The following snippet
```markdown
Lorem ipsum.

![Caption][fig1]

Lorem ipsum.

[fig1]: sample.png
```
produces
```html
<p>Lorem ipsum.</p>

<figure>
<img src="sample.png" alt="Caption" id="fig1" />
<figcaption>Caption</figcaption>
</figure>

<p>Lorem ipsum.</p>
```
which is fine. But if i I delete the image definition or if I use it incorrectly like in the following two examples
```markdown
Lorem ipsum.

![Caption][fig1]

Lorem ipsum.
```
```markdown
Lorem ipsum.

![Caption][fig0]

Lorem ipsum.

[fig1]: sample.png
```
this HTML is produced:
```html
<p>Lorem ipsum.</p>

<figure>
![Caption][fig1]

<p>Lorem ipsum.</p>
```
```html
<p>Lorem ipsum.</p>

<figure>
![Caption][fig0]

<p>Lorem ipsum.</p>
```
The `figure` tag isn't closed which prevents further processing in tools which demand well-formed XML.

I'm of course guilty of wrong markdown syntax, but it would be very nice if MultiMarkdown would just close the `figure` tag in such cases.

**Comment by fletcher** [comment]
Thanks!

**Comment by mn4367** [comment]
Thank you! :-)
