### ISSUE TITLE
![Alt text](/path/to/img.jpg "Optional title") syntax currently broken

### ISSUE THREAD

**Issue by mn4367** [fletcher/MultiMarkdown-4#123]
This input (taken from the documentation)
```markdown
![Alt text](/path/to/img.jpg "Optional title")
```
produces
```html
<img src="/path/to/img.jpg" alt="Alt text" title="Optional title" />
<figcaption>Alt text</figcaption>
</figure>
```
which has no opening `figure` tag. It happens with the latest sources, I haven't tested it with release 4.7.1, but maybe it's related to the fix you introduced in #121.

**Comment by fletcher** [comment]
Thanks for pointing this out!
