### ISSUE TITLE
Incorrect works code blocks?

### ISSUE THREAD

**Issue by Skif-off** [fletcher/MultiMarkdown-4#129]
For example https://github.com/gelobi/Griddify/blob/master/docs/manual-install.md
Lines: 45 and +49-53, 58-63.

**Comment by fletcher** [comment]
I don't understand.

**Comment by Skif-off** [comment]
Unfortunately my English is bad, in a few words:

    Open the Terminal application (normally stored in the `/Applications/Utilities` folder)
    
    ```/usr/libexec/PlistBuddy -c “print” ~/Library/Preferences/com.adobe.CSXS.5.plist```
    
    The output should look like this:
    
    ```
    Dict {
       LogLevel = 1
    }
    ```
    
    * To confirm that the entry has beew key:
    	```
    	Dict {
    		PlayerDebugMode = 1
    		LogLevel = 1
    	}
    	```
    
    ## Manually
please convert into HTML.

**Comment by fletcher** [comment]
Got it.

1) I will look at this.

2) A fix (for now) is to change number of backticks (4 instead of 3):

	````/usr/libexec/PlistBuddy -c “print” ~/Library/Preferences/com.adobe.CSXS.5.plist````

	The output should look like this:

	```
	Dict {
	   LogLevel = 1
	}
	```
