### ISSUE TITLE
Can you add support strikethrough text?

### ISSUE THREAD

**Issue by Skif-off** [fletcher/MultiMarkdown-4#130]
GitHub Flavored Markdown adds syntax to create strikethrough text:
```
~~Mistaken text.~~
```
~~Mistaken text.~~

**Comment by fletcher** [comment]
MMD handles strikethroughs via the CriticMarkup approach -- this is a different approach, but I believe that in general, it's a better one.  Please see the User's Guide for more information.  At this time, I do not anticipate adding generic strike through support like GFM.

<http://fletcher.github.io/MultiMarkdown-4/criticmarkup.html>
