### ISSUE TITLE
Ampersand in bibliographical references is not converted to &amp;.

### ISSUE THREAD

**Issue by ajbuch2000** [fletcher/MultiMarkdown-4#136]
An mmd file with just `[#&z]` in it does not convert the & to `&amp;`, so the odf file can't be read. `[&z]` works fine, but `[][&z]` doesn't. Of course, having an ampersand in a link is probably a mistake, but LibreOffice gives no clue why it won't read the file, so having illegal xml is not the friendliest way to find out.

**Comment by fletcher** [comment]
I can't replicate this in latest version of MMD.
