### ISSUE TITLE
Problems with spaces after footnotes in .FODT output

### ISSUE THREAD

**Issue by iandol** [fletcher/MultiMarkdown-4#137]
Not sure if this is a bug in LibreOffice, but if I have the following MMD:

```
One striking feature of these networks is that the numbers of connections originating *from* the sense organs like the eyes are often matched or greatly exceeded by connections feeding-back from within the brain itself[^cf2]. This fact is in contrast to common naïve intuition and traditional reflex models which expect the brain to be responding mainly to inputs from the outside world to generate behavioural responses.

[^cf2]: {Felleman and Van Essen, 1991, #6227; Budd, 2004, #1069}
```

It generates this XML:
```(xml)
One striking feature of these networks is that the numbers of connections originating <text:span text:style-name="MMD-Italic">from</text:span> the sense organs like the eyes are often matched or greatly exceeded by connections feeding-back from within the brain itself<text:note text:id="" text:note-class="footnote"><text:note-body>
<text:p text:style-name="Footnote">{Felleman and Van Essen, 1991, #6227; Budd, 2004, #1069}</text:p>
</text:note-body>
</text:note>
. This fact is in contrast to common naïve intuition and traditional reflex models which expect the brain to be responding mainly to inputs from the outside world to generate behavioural responses.
```
But the display in LibreOffice adds a space between the footnote and the fullstop. 
![screen shot 2015-09-08 at 12 37 30](https://cloud.githubusercontent.com/assets/153905/9733885/d3f0d066-5626-11e5-8bcb-6a19fd6b58b4.png)
I'm not an expert of the ODF format at whether newlines should be converted into spaces. Anyway not padding your FODT footnote elements with newlines fixes this issue.

**Comment by iandol** [comment]
This: http://books.evc-cit.info/odbook/ch03.html#whitespace-section suggest OpenDocument collapses successive whitespace into a single space, but the newline in the XML is singular not consecutive? Perhaps consecutive mean 1-n

**Comment by fletcher** [comment]
I'll look at this, but I believe footnotes are supposed to be used *after* periods, commas, etc.  In this case, the spacing becomes irrelevant because it would be collapsed with the following space.

**Comment by iandol** [comment]
Ha, interesting. I'm using footnotes for scientific references, and for this the footnote should precede punctuation like periods and commas — this is how major journals like Nature, Science, PNAS etc.  format display reference footnotes.

Example: http://www.nature.com/nature/journal/vaop/ncurrent/full/nature14900.html
