### ISSUE TITLE
Rogue Bibliography on ODF output

### ISSUE THREAD

**Issue by iandol** [fletcher/MultiMarkdown-4#90]
When I output (document written in Scrivener) to flat ODF, I notice in the Navigator there is a rogue bibliography section:
![screen shot 2014-11-23 at 10 33 53](https://cloud.githubusercontent.com/assets/153905/5156446/876b8cf2-72fd-11e4-8900-cc36b4369d68.png)
I can't find any heading in the document that matches this rogue entry. I do see in the raw fodt file the following:

``` xml
<office:master-styles>
  <style:master-page style:name="Endnote" >
    <style:header><text:h text:outline-level="2">Bibliography</text:h></style:header></style:master-page>
  <style:master-page style:name="Footnote" style:page-layout-name="pm2"/>
 </office:master-styles>
```

This is somehow leaking into the document structure, I don't understand odt format but I imagine this is a bug in Libreoffice. I don't understand what the master-style section does, but can I control removing it when MMD generates its output (simple deletion causes a loading error)? I have lots of other little things I'd like to change (which I currently do using regexes), and the MMD manual suggests I can customise ODT output but I don't know where to start.

**Comment by iandol** [comment]
@fletcher — the rogue header is still being added to all FODT output. The problem is there is a <text:h> element (line 255 of you doc fodt) that is being read. Here is you MMD documentation with the rogue heading:
![screen shot 2015-09-08 at 15 10 09](https://cloud.githubusercontent.com/assets/153905/9737001/5730ac16-563c-11e5-9053-354cf6b572da.png)

Is this a bug with LibreOffice?

**Comment by fletcher** [comment]
This seems to be a problem with OpenOffice/LibreOffice, but I haven't looked into it since my original response.

**Comment by iandol** [comment]
Here is the part of the text where the header element is inserted into the styles section for whatever reason:

https://github.com/fletcher/MultiMarkdown-4/blob/master/odf.c#L1231

Note, I remove the <text:h text:outline-level="2">Bibliography</text:h> manually from the FODT and this "fixes" the rogue header, but I don't understand what it is doing in styling XML in the first place. I'll post a bug on the LibreOffice bugzilla, perhaps they know why there is a <text:h> element in this styling code?

**Comment by iandol** [comment]
In a new FODT created by LibreOffice Writer, this is the master-styles section, it doesn't contain any text headers:

```xml
<office:master-styles>
  <style:master-page style:name="Standard" style:page-layout-name="pm1"/>
 </office:master-styles>
```

**Comment by iandol** [comment]
OK, so you're creating an endnote page style which has a "heading-2" in the page header with the text "Bibliography", I can recreate this denovo using V5.02 of LibreOffice, and the same thing happens in Navigator and PDF output, so I've created a 
LibreOffice bug for this behaviour: https://bugs.documentfoundation.org/show_bug.cgi?id=94345

The workaround is either to ignore it and all documents produced by MMD->ODT have this, or remove the header until this is fixed.
