### ISSUE TITLE
Getting rid of listings in favor of minted for LaTeX code blocks

### ISSUE THREAD

**Issue by marco-m** [fletcher/MultiMarkdown-4#99]
Hi,
mmd uses the listings package to format code blocks. Listings is quite limited; in particular it doesn't do colors.
I would propose replacing listings with minted (https://github.com/gpoore/minted), which uses the very powerful Python library Pygments.
The only problem is that it adds the dependency on Pygments, which for me is not a problem, but you might consider it so.
Anyway, I will add support to it and then send a pull request, so you'll tell me if it makes sense or not.
And, thanks for mmd! :-)

**Comment by fletcher** [comment]
I don't want to add more dependencies to MMD, but others may certainly be interested if you share your work.

**Comment by marco-m** [comment]
Sure, I understand your point of view.
